# Generated by Django 5.2.12 on 2026-03-13 04:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('TOP_MANAGEMENT', 'Top Management'), ('MANAGER', 'Manager'), ('AGENT', 'Agent')], default='AGENT', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CallReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('date_processed', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(max_length=50)),
                ('system_processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('candidates_tokens', models.IntegerField(blank=True, null=True)),
                ('cost_thb', models.FloatField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QACategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('call_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_categories', to='qa_dashboard.callreport')),
            ],
        ),
        migrations.CreateModel(
            name='QAQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=10)),
                ('question', models.CharField(max_length=255)),
                ('criteria', models.TextField()),
                ('answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], max_length=10)),
                ('evidence', models.TextField(default='N/A')),
                ('explanation', models.TextField()),
                ('qa_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qa_dashboard.qacategory')),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=50)),
                ('speaker', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('emotion', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Sequential order of the utterance in the call')),
                ('call_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='qa_dashboard.callreport')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
