# Generated by Django 4.2.24 on 2026-03-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callreport',
            name='overall_score',
            field=models.FloatField(default=0.0, help_text='Denormalized QA score'),
        ),
    ]
