# Generated by Django 4.2.24 on 2026-03-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_dashboard', '0002_callreport_overall_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callreport',
            name='date_processed',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('TOP_MANAGEMENT', 'Top Management'), ('MANAGER', 'Manager'), ('AGENT', 'Agent')], db_index=True, default='AGENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='language',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='speaker',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
